# .devcontainer/docker-compose.yml
# version: '3.8'

services:
  smart_dev:
    build:
      context: ../
      dockerfile: .devcontainer/Dockerfile
      args:
        BASE_IMAGE: "nvidia/cuda:12.8.0-runtime-ubuntu24.04"
    image: smart-dev:latest
    container_name: SmartDev

    # Keep container alive for VS Code server
    command: sleep infinity
    stdin_open: true
    tty: true

    # ─── GPU support (all GPUs) ───
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

    # ─── Mounts ───
    volumes:
      # 1) Project root (one level up from .devcontainer) → /workspaces/smart_dev
      - ..:/workspaces/smart_dev:rw

      # 2) Your Windows user folder → /mnt/hostuser
      - /mnt/c/Users/cml_p:/mnt/hostuser:cached

      # 3) G-drive mount → /mnt/gdrive
      - /mnt/g:/mnt/gdrive:cached

    #EXTENSION: add future volumes, networks, or profiles here
