# .devcontainer/docker-compose.yml
# version: '3.8'

services:
  smart_dev:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
      args:
        BASE_IMAGE: "nvidia/cuda:12.8.0-runtime-ubuntu24.04"
    image: smart-dev:latest
    container_name: SmartDev

    # Keep container alive for VS Code server
    command: sleep infinity
    stdin_open: true
    tty: true

    # GPU support (all GPUs)
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all        # use all available GPUs
              capabilities: [gpu]

    # Host mounts (with caching for WSL2)
    volumes:
      - /mnt/c/Users/cml_p:/mnt/hostuser:cached
      - /mnt/g:/mnt/gdrive:cached

    #EXTENSION: add future volumes, networks, or profiles here
